### ISSUE TITLE
Update and install fail for me after latest atom update

### ISSUE THREAD

**Issue by LeeDoty** [sverweij/atom-state-machine-cat-preview#11]
### Expected Behavior
be able to update atom plugin after updating atom

### Current Behavior
I updated atom to 1.43.0 x64 on mac high sierra
I then tried to update my smcat plugin to the current version 4.6.9
The update failed.
I then uninstalled the plugin and tried to install it fresh.  That also failed.  Here are the contents of the atom error log:

0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/ldotyjr/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/ldotyjr/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/state-machine-cat-preview/versions/4.6.9/tarball',
1 verbose cli   '--target=4.2.7',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v10.2.1
4 verbose npm-session 53d87bf89daf51ea
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://www.atom.io/api/packages/state-machine-cat-preview/versions/4.6.9/tarball 1411ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/state-machine-cat-preview/versions/4.6.9/tarball fetched in 1430ms
9 timing stage:loadCurrentTree Completed in 1566ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule state-machine-cat-preview@4.6.9 checking installable status
17 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning UNABLE_TO_VERIFY_LEAF_SIGNATURE: request to https://registry.npmjs.org/state-machine-cat failed, reason: unable to verify the first certificate
18 warn registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
19 http fetch GET 200 https://registry.npmjs.org/atom-space-pen-views 344ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/underscore-plus 344ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/fs-plus 345ms (from cache)
22 silly pacote version manifest for atom-space-pen-views@2.2.0 fetched in 350ms
23 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
24 silly pacote version manifest for underscore-plus@1.7.0 fetched in 348ms
25 silly resolveWithNewModule underscore-plus@1.7.0 checking installable status
26 silly pacote version manifest for fs-plus@3.1.1 fetched in 350ms
27 silly resolveWithNewModule fs-plus@3.1.1 checking installable status
28 http fetch GET 200 https://registry.npmjs.org/state-machine-cat 350ms (from cache)
29 silly registry:manifest no matching version for state-machine-cat@6.0.1 in the cache. Forcing revalidation
30 http fetch GET 200 https://registry.npmjs.org/state-machine-cat 281ms (from cache)
31 silly fetchPackageMetaData error for state-machine-cat@6.0.1 No matching version found for state-machine-cat@6.0.1
32 timing stage:rollbackFailedOptional Completed in 0ms
33 timing stage:runTopLevelLifecycles Completed in 2219ms
34 silly saveTree apm-install-dir-120025-3720-5ygcl4.9krv6
34 silly saveTree `-- state-machine-cat-preview@4.6.9
34 silly saveTree   +-- atom-space-pen-views@2.2.0
34 silly saveTree   +-- fs-plus@3.1.1
34 silly saveTree   | `-- underscore-plus@1.7.0
34 silly saveTree   `-- underscore-plus@1.7.0
35 verbose type version
36 verbose stack state-machine-cat: No matching version found for state-machine-cat@6.0.1
36 verbose stack     at pickManifest (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/npm-pick-manifest/index.js:65:11)
36 verbose stack     at fetchPackument.then.packument (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
36 verbose stack     at tryCatcher (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
36 verbose stack     at Promise._settlePromiseFromHandler (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
36 verbose stack     at Promise._settlePromise (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
36 verbose stack     at Promise._settlePromise0 (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
36 verbose stack     at Promise._settlePromises (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
36 verbose stack     at Async._drainQueue (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
36 verbose stack     at Async._drainQueues (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
36 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
36 verbose stack     at runCallback (timers.js:696:18)
36 verbose stack     at tryOnImmediate (timers.js:667:5)
36 verbose stack     at processImmediate (timers.js:649:5)
37 verbose cwd /private/var/folders/3p/65r6_98d26zcxfstw3q73zc00000gn/T/apm-install-dir-120025-3720-5ygcl4.9krv6
38 verbose Darwin 17.7.0
39 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ldotyjr/.atom/.apm/.apmrc" "--userconfig" "/Users/ldotyjr/.atom/.apmrc" "install" "https://www.atom.io/api/packages/state-machine-cat-preview/versions/4.6.9/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
40 verbose node v10.2.1
41 verbose npm  v6.2.0
42 error code ETARGET
43 error notarget No matching version found for state-machine-cat@6.0.1
44 error notarget In most cases you or one of your dependencies are requesting
44 error notarget a package version that doesn't exist.
44 error notarget
44 error notarget It was specified as a dependency of 'state-machine-cat-preview'
45 verbose exit [ 1, true ]

### Possible Solution
no idea

### Steps to Reproduce (for bugs)
see "current behavior above"

### Context
I've now got no way to use this plugin with atom

### Your Environment
see "current behavior above"

**Comment by sverweij** [comment]
Hi @LeeDoty I've tried to replay this (with a fresh install of atom 1.43) but wasn't able to. From the log I infer this:
- most of the package retrievals seem to occur locally (from cache)
- it complains `36 verbose stack state-machine-cat: No matching version found for state-machine-cat@6.0.1` - state-machine-cat@6.0.1 _does_ exist on npm, though

It seems the npm/ apm cache on your machine is a bit confused after the update.
