### ISSUE TITLE
An error occurs after update Please fix it.

### ISSUE THREAD

**Issue by kimokhun** [sverweij/atom-state-machine-cat-preview#6]
process.smcat preview
whiteblacktransparent
-100%+
Zoom to fit
error Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

**Comment by sverweij** [comment]
hi @kimokhun - thanks for raising this issue.

I've tried to reproduce it, but weren't able to with the latest version and the state machine descriptions I have at my disposal. This means there's either something different in your installation or something specific to the state machine you're trying to render. 

Hence, could you provide me with:
- the version of atom-state-machine-cat-preview you're using
- the contents of `process.smcat` you got this error with
- (the version of atom and the platform you're using)

**Comment by kimokhun** [comment]
[image: 본문 이미지 1]


   1. State Machine Cat Preview  version 1.5.2



*error smcat file : *
process.smcat


<https://mail.google.com/mail/u/0/?ui=2&ik=5663c29ab6&view=att&th=160f428555bf6dae&attid=0.1&disp=safe&realattid=f_jcemgup11&zw>atom
version : 1.9.9


2018-01-14 19:08 GMT+09:00 Sander Verweij <notifications@github.com>:

**Comment by sverweij** [comment]
You might want to update your atom version to a more recent one; 1.9.9 is from august 2016 - the latest one is from ~ a week ago (currently 1.23.3). It's not unlikely that once you upgrade the problem will be gone. (You'll probably be happy with the improvements the atom maintainers made in the past year). 

I also see you tried to upload the `.smcat` that reproduced the error, but for one reason or other it didn't end up on GitHub. If updating atom didn't help could you paste the contents in a comment?
